### ISSUE TITLE
How to deal with the time dimension of the input..

### ISSUE THREAD

**Issue by wangshuo1994** [coolsunxu/Scale_Net#1]
Hi, I am sorry because I am asking a very stupid question. Could you please tell me how to deal with the time dimension in the input, because in the test of the code, x is a 2-dimensional matrix without a time dimension. (I suppose the input tensor has a shape of the number of surrounding vehicles * the number of features * length of history time). Thank you in advance!

**Comment by coolsunxu** [comment]
There is lstm in the middle, and the processed input is used as the input of each time step of LSTM in turn

**Comment by coolsunxu** [comment]
> 
> 
> Hi, I am sorry because I am asking a very stupid question. Could you please tell me how to deal with the time dimension in the input, because in the test of the code, x is a 2-dimensional matrix without a time dimension. (I suppose the input tensor has a shape of the number of surrounding vehicles * the number of features * length of history time). Thank you in advance!

There is lstm in the middle, and the processed input is used as the input of each time step of LSTM in turn
